myapp/__init__.py
''' Este archivo se utiliza para realizar la importacion de las configuraciones globales
    tales como la importacion de la app, las rutas generales del proyecto, definir si el
    servidor corre en modo debug, Registro de la BD, etc.'''
from flask import Flask, render_template, request
from myapp.config import DevConfig
from myapp.task.controllers import taskRoute

app = Flask(__name__) #template_folder="/pages"
app.register_blueprint(taskRoute)
#app.debug = True
app.config.from_object(DevConfig)

@app.route('/')
def hello_world() -> str:
    name = request.args.get('name', 'Valor por defecto')
    return render_template('index.html', task="Josue", name=name)

myapp/task/__init__.py
#nombre hecho con base a la nomenclatura, los quiones bajos significa que se va a hacer una configuracion

myapp/task/controllers.py
from flask import Blueprint, render_template, request, redirect, url_for

taskRoute = Blueprint('task', __name__, url_prefix='/task')  # Uso de __name__ en lugar de _name_
task_list = ['tasks 1', 'tasks 2', 'tasks 3']

# Ruta para mostrar todas las tareas
@taskRoute.route('/')
def index():
    return render_template('dashboard/task/index.html', tasks=task_list)

# Ruta para mostrar una tarea específica por ID
@taskRoute.route('/<int:id>')
def show(id: int):
    return 'Show ' + str(id)

# Ruta para eliminar una tarea específica
@taskRoute.route('/delete/<int:id>')
def delete(id: int):
    if id is not None and 0 <= id < len(task_list):  # Verificación de índice válido
        del task_list[id]
    return redirect(url_for('task.index'))

# Ruta para crear una nueva tarea
@taskRoute.route('/create', methods=('GET', 'POST'))
def create():
    task = request.form.get('task')
    if task is not None and task != "":  # verifica que no venga vacia 
        task_list.append(task)
        return redirect(url_for('task.index'))
    return render_template('dashboard/task/create.html')

# Ruta para actualizar una tarea específica
@taskRoute.route('/update/<int:id>', methods=['GET', 'POST'])
def update(id: int):
    task = request.form.get('task')
    if task is not None and task != "" and 0 <= id < len(task_list):  # Verificación de índice válido
        task_list[id] = task
        return redirect(url_for('task.index'))
    return render_template('dashboard/task/update.html')

myapp/templates/dashboard/master.html
<!-- Ese es el Template que se va a utilizar para elel Dashboard -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock%} - Flask</title>
</head>
<body>
    <div>
        {%block content%}
        {% endblock %}
    </div>
    {% block footer%}
        <p> footer Dashboard </p>
    {% endblock %}
</body>
</html>

myapp/templates/dashboard/task/create.html
{% extends "dashboard/master.html"%}
{% block title%} Create task {%endblock%}
{% block content%} 
    <form action="" method="post">
        <input type="text" name="task" id="">
        <button type="submit"> Send </button>
    </form>
    
    
{%endblock%}

myapp/templates/dashboard/task/index.html
<!--Todas las paginas de usuario que van a pertenercer al dashbord van a heredar de la plantilla maestra del dashboard-->
{% extends "dashboard/master.html"%}
{% block title%} Index task {%endblock%}
{% block content%} 
    <ul>
        {% for t in tasks %}
        <li>{{ t }}</li>
        {#<li><a href="/task/update/{{loop.index0}}"> Edit </a></li> Dentro del loop va obteniendo el index de cada iteracion#}
        <li><a href="{{ url_for('task.update',id=loop.index0)}}"> Edit </a></li> {#Task es el nombre definido en el BluePrint del controller#}
        <li><a href="{{ url_for('task.delete',id=loop.index0)}}"> Delete </a></li> {#Task es el nombre definido en el BluePrint del controller#}
        {% endfor %}
    </ul>
{%endblock%}

myapp/templates/dashboard/task/update.html
<!--Todas las paginas de usuario que van a pertenercer al dashbord van a heredar de la plantilla maestra del dashboard-->
{% extends "dashboard/master.html"%}
{% block title%} Update task {%endblock%}
{% block content%} 
    <form action="" method="post">
        <input type="text" name="task" id="">
        <button type="submit"> Send </button>
    </form>
    
    
{%endblock%}

myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Template example </h1>
    <p> Hello Flask </p>
    {% if True %}
        <p>{{ name }}</p>
    {% else %}
        <p>Sin datos</p>
    {%endif%}
    <h1> Bucle de control</h1>
    <ul>
        {% for i in [1,2,3,4,5,6,7,8,9,10]%}
            <li>{{ i }}</li>
        {%endfor%}
    </ul>
    <h1> Filtros</h1>
    <p> {{task | default('No hay Tarea')}}</p>
    {%if task | default('No hay tarea') == 'Josue' %}
        <p>Tenemos Data</p>
    {%endif%}
    <!--Comentarios-->
     {#if task | default('No hay tarea') == 'Josue' #}
        <!--<p>Tenemos Data</p>-->
    {#endif#} 
    <p> {{ 5.1324 | int}}</p>
    <p> {{ 5.1324 | float}}</p>
    <p> {{ [1,2,3,4,5,6,7] | min}}</p>
    <p> {{ [1,2,3,4,5,6,7] | max}}</p>
    <p> {{ 6.141 | round}}</p>
    <p> {{ 6.14123 | round(2)}}</p>
    <p> {{ "Hello Flask" | replace("Hello", "Hi")}}</p>
    <p> {{ ["Hello Flask", "Hola", "Mundo", 5] | join(" ")}}</p>
    <p> {{ "Hello Flask" | lower}}</p>
    <p> {{ "Hello Flask" | upper}}</p>
    {%filter lower%}
        Hello World
    {% endfilter %}
    <p> {{ "Hello Flask" | reverse}}</p>
    {% for i in [1,2,3,4,5,6,7,8,9,10] | reverse%}
            <li>{{ i }}</li>
    {%endfor%}
    <p> {{ "Hello Flask" | length}}</p>
    <p> {{ [1,2,3,4,5,6,7] | length}}</p>
    {% for i in [1,-2,3,4,-5,6,50,8,22,10] | sort%}
            <li>{{ i }}</li>
    {%endfor%}
    <h3>Sublistas</h3>
    {% for i in [1,-2,3,4,-5,6,50,8,22,10] | slice(3)%}
            <li>{{ i }}</li>
    {%endfor%}
    <h3>Variables</h3>
    {%set var1 = 'Flask'%}
    {%set var2 = var1%}
    {{ var1 }}
    {{ var2 }}
    <h3>Macros</h3>
    {%macro suma(v1, v2)%}
        <p>{{v1}} + {{v2}} = {{v1+v2}}</p>
    {%endmacro%}
    {{suma(3,4)}}
</body>
</html>